export enum Message {
  BUTTON_BACK = 'button.back',
  BUTTON_ASK_PHONE_NUMBER = 'button.ask_phone_number',
  BUTTON_SETTINGS_NAME = 'button.settings_username',
  BUTTON_ASK_SETTINGS_PHONE = 'button.ask_settings_phone',
  BUTTON_SETTINGS_PHONE = 'button.settings_phone',
  BUTTON_SETTINGS_LAGNUAGE = 'button.settings_language',
  BUTTON_ORDER = 'button.order',
  BUTTON_SETTINGS = 'button.settings',
  BUTTON_SEND_LOCATION = 'button.send_location',
  BUTTON_CONFIRM_LOCATION = 'button.confirm_location',
  BUTTON_DELIVERY = 'button.delivery',
  BUTTON_PICKUP = 'button.pickup',
  BUTTON_MY_LOCATIONS = 'button.my_locations',
  BUTTON_MENU = 'button.menu',

  WRONG_FORMAT = 'wrong_format',
  SEND_PHONE = 'send_phone',
  SEND_NAME = 'send_name',
  ADDRESS_NOT_FOUND = 'address_not_found',
  CLICK_START = 'click_start',
  SEND_LOCATION = 'send_location',
  MY_LOCATION = 'my_location',
  CHOOSE_ORDER_TYPE = 'choose_order_type',
  CHOOSE_ACTION = 'choose_action',
  SUCCESFULLY_DONE = 'succesfully_done',
  RESET = 'reset',
  ASK_PHONE_NUMBER = 'ask_phone_number',
  LANGUAGE_SETTES = 'language_set',
  WRONG_ACTION = 'wrong_action',
  PHONE_NUMBER_ALREADY_EXISTS = 'phone_number_already_exists',
  WRONG_PHONE_NUMBER = 'wrong_phone_number',
  BUTTON_HISTORY = 'button.history',
  CHOOSE_LANGUAGE = 'Tilni tanlang:\n\n Choose language:\n\n Bыберите язык:\n',
  NO_HISTORY = 'no_history',
}
