export enum Message {
  // sdsd.ds
  ASK_PHONE_NUMBER = 'ask_phone_number',
  LANGUAGE_SETTES = 'language_set',
  ASK_PHONE_NUMBER_BUTTON = 'ask_phone_number_button',
  WRONG_ACTION = 'wrong_action',
  PHONE_NUMBER_ALREADY_EXISTS = 'phone_number_already_exists',
  SETTINGS_NAME = 'sattings_name',
  SETTINGS_PHONE = 'settings_phone',
  SETTINGS_LAGNUAGE = 'settings_language',
  BACK = 'back',
  WRONG_PHONE_NUMBER = 'wrong_phone_number',
  SETTINGS = 'settings',
  ORDER = 'order',
  DELIVERY = 'delivery',
  PICKUP = 'pickup',
  SEND_LOCATION = 'send_location',
  MY_LOCATIONS = 'my_locations',
  CONFIRM_LOCATION = 'confirm_location',
  MENU = 'menu',
  HISTORY = 'hostory',
}
